#undef PACKAGE
#undef VERSION
#undef HAVE_LIBSM
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef ENABLE_NLS

#undef GNOME_ICONDIR

#undef ID3LIB_MAJOR
#undef ID3LIB_MINOR
#undef ID3LIB_PATCH
#undef HAVE_ID3LIB
