.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH GRIP 1 "Gtk Applications" "7/Nov/1999" " "
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
grip \- A gtk-based cd-player and cd-ripper.
.PP
gcd \- A gtk-based cd-player (used as part of grip, or alone).
.SH "SYNOPSIS"
.PP
.Vb 1
\&  grip [-d <device>] [-s] [-l]
.Ve
.Vb 1
\&  gcd [-d <device>] [-f] [-l]
.Ve
.SH "DESCRIPTION"
Grip is a gtk-based cd-player and cd-ripper. It has the ripping capabilities
of cdparanoia builtin, but can also use external rippers (such as
cdda2wav). It also provides an automated frontend for MP3 encoders, letting
you take a disc and transform it easily straight into MP3s. The CDDB
protocol is supported for retrieving track information from disc database
servers. Grip works with DigitalDJ to provide a unified \*(L"computerized\*(R"
version of your music collection. GCD is the cd-player only version of Grip.
.PP
Because Grip and GCD share much of their functionality, this file documents
both of them. If you installed only GCD, you should ignore the bits that
talk about \*(L"ripping\*(R" and \*(L"encoding\*(R" of tracks.
.PP
Grip is designed to work closely with DigitalDJ, my SQL\-based mp3 jukebox
system (although it does not require it). DigitalDJ can be obtained from:
.PP
.Vb 1
\&  http://www.nostatic.org/ddj
.Ve
.SH "OPTIONS"
These are the command-line options for grip:
.Ip "\f(CW-d <device>\fR" 5
Use <device> as the cd-rom device (default: \f(CW/dev/cdrom\fR).
.Ip "\f(CW-s\fR" 5
Launch grip in a \*(L"small\*(R" (cd-only) mode.
.Ip "\f(CW-l\fR" 5
\*(L"local\*(R" mode -- don't try to use \s-1CDDB\s0.
.Ip "\f(CW-v\fR" 5
Verbose (debug) mode.
.PP
These are gcd's command-line options:
.Ip "\f(CW-d <device>\fR" 5
Use <device> as the cd-rom device (default: \f(CW/dev/cdrom\fR).
.Ip "\f(CW-f\fR" 5
Launch gcd in \*(L"full\*(R" (track-display) mode.
.Ip "\f(CW-l\fR" 5
\*(L"local\*(R" mode -- Don't try to use \s-1CDDB\s0.
.Ip "\f(CW-v\fR" 5
Verbose (debug) mode.
.SH "USAGE"
The most handy way to launch Grip/GCD is from your window manager's doc. A
dock icon (\f(CWgripicon.tif\fR/\f(CWgcdicon.tif\fR) is included with the distribution.
.PP
Grip's operation should be pretty self-explanatory. Tracks to rip are
selected with the right mouse button. To select all tracks on the disc,
click the \*(L"Rip\*(R" column label. When you select \*(L"Rip\*(R" or \*(L"MP3-encode\*(R" from the
\*(L"Rip\*(R" page, Grip will rip or rip/encode the tracks you have selected. If you
select \*(L"Rip partial track\*(R", only the current select of the current track
will be ripped or encoded. Start/End sector values are ignored if partial
track ripping is not enabled.
.PP
Grip and GCD used to be installed as setuid root. This was for several
reasons. First, most people have their systems configured such that their
user account does not have access to the cd drive. Secondly, cdparanoia
requires access to both the cd device and (for SCSI drives) the generic SCSI
device (usually \f(CW/dev/sg\fR<something>). Despite this, I no longer install the
programs setuid root. This means that you will have to set the permissions
correctly on the appropriate devices, or run the program as root.
.PP
\fBIMPORTANT!\fR
.PP
If you have trouble with Grip or GCD, read the \*(L"Common Questions\*(R"
section. I'm getting bogged down in email these days. This being said, I do
appreciate feedback on Grip. If, after reading through this document
carefully, you still have a question, or have a feature request, feel free
to email me. Do read the file TODO first, however, to check whether it's
already on my list.
.PP
\fBIMPORTANT!\fR
.SH "CONFIGURATION"
The \*(L"Config\*(R" menu allows you to configure your ripping program and your CDDB
database. Rip/Encode/ID3 options are only available in Grip.
.PP
Here are the options:
.Sh "\s-1CD\s0 options:"
.Ip "Don't interrupt playback on exit/startup" 5
If this is not selected, Grip
will stop play when it starts
and when it stops.
.Ip "Rewind when stopped" 5
If selected, Grip will rewind to the first track
when play is stopped.
.Ip "Startup with first track if not playing" 5
If this is not selected, Grip
will begin with whatever track
the cd-player played last.
.Ip "Reshuffle before each playback" 5
If selected, Grip will re-randomize the
tracks each time playback begins when in
shuffle-play mode.
.PP
Rip Options:
.Ip "\fBRipper\fR" 5
This allows you to select one of the preset rippers. This will
fill in sensible default parameters for calling the ripper. If
you select \*(L"grip (cdparanoia)\*(R", Grip will use its builtin version
of cdparanoia (only available if paranoia has been compiled
in). If the builtin ripper is selected, the following options are
available:
.Ip "Disable paranoia" 5
Disables all paranoia checking.
.Ip "Disable extra paranoia" 5
Only cdda2wav-style overlap checking will be done.
.Ip "Disable scratch detection" 5
Do not look for scratches.
.Ip "Disable scratch repair" 5
Disable scratch repair (still detect)
.Ip "Ripping executable" 5
This should be the full path to the program you want to use to rip tracks with.
.Ip "Ripping command-line" 5
These are the arguments that will be passed to the ripping program. The
\&'\f(CW%\fR\*(R' switches are translated as follows:
.Ip "\f(CW%t\fR" 10
Track to be ripped
.Ip "\f(CW%b\fR" 10
Begin sector to be ripped (0 is start of track) 
.Ip "\f(CW%e\fR" 10
End sector of track
.Ip "\f(CW%f\fR" 10
Filename to put \f(CW.wav\fR data to
.Ip "Rip file format" 5
This specifies the format of the filename to write
ripped data to. The \*(L'%\*(R' switches are translated as
follows:
.Ip "\f(CW%n\fR" 10
Name of track being ripped
.Ip "\f(CW%t\fR" 10
Number of track being ripped
.Ip "\f(CW%a\fR" 10
Artist of current track
.Ip "\f(CW%A\fR" 10
Artist of the current disc
.Ip "\f(CW%d\fR" 10
Name of current disc
.Ip "\f(CW%b\fR" 10
Begin sector to be ripped (0 is start of track) 
.Ip "\f(CW%e\fR" 10
End sector of track
.Ip "\f(CW%c\fR" 10
cdrom device
.Ip "\f(CW%i\fR" 10
\s-1CDDB\s0 discid in hex format
.Ip "\f(CW%g\fR" 10
\s-1ID3\s0 genre tag as a number
.Ip "\f(CW%G\fR" 10
\s-1ID3\s0 genre tag as a word
.Sp
Adding a \*(L'*\*(R' between the \*(L'%\*(R' and the switch will cause
underscoring of the field to be skipped.
.Ip "Rip \*(N'nice\*(T' value" 5
The \*(L'nice\*(R' (priority) level to run the rip at.
.Ip "Max non-encoded \f(CW.wav\fR's" 5
The maximum number of non-encoded \f(CW.wav\fR files grip will keep around before
pausing ripping.
.Ip "Auto-rip on insert" 5
If selected, Grip will automatically select all
tracks and begin ripping when a new (ie: no local
disc data) disc is inserted.
.Ip "Auto-eject after rip" 5
If selected, Grip will automatically eject the disc
when ripping is finished.
.Ip "Wav filter command" 5
This command will be run after ripping but before
encoding. It can be used to call a program to
manipulate the .wav file in some way (such as doing
normalization). It accepts a single switch, \f(CW%f\fR, which
translates as the ripped .wav file.
.Sh "\s-1MP3\s0 options:"
.Ip "Encoder" 5
This allows you to select one of the preset rippers. This will
fill in sensible default parameters for calling the encoder.
.Ip "\s-1MP3\s0 executable" 5
This should be the full path to the program you want
to use to \s-1MP3-\s0encode tracks with.
.Ip "\s-1MP3\s0 command-line" 5
These are the arguments that will be passed to the
\s-1MP3\s0 encoder. The \*(L'%\*(R' switches are translated as
follows:
.Ip "\f(CW%b\fR" 10
Encode bitrate (kbits/sec)
.Ip "\f(CW%f\fR" 10
Filename of the .wav data to be encoded
.Ip "\f(CW%o\fR" 10
Filename to save mp3 data to
.Ip "\s-1MP3\s0 file format" 5
This specifies the format of the filename to write
\s-1MP3\s0 data to. The \*(L'%\*(R' switches are the same as those
used in the rip file format.
.Ip "Delete \f(CW.wav\fR after encoding?" 5
If selected, this option will (surprise!)
delete the ripped .wav file after encoding.
.Ip "Insert into \s-1SQL\s0 database" 5
If selected, and DigitalDJ is installed, Grip
will place the song information into
DigitalDJ's song database.
.Ip "Number of CPUs to use" 5
This is the number of simultaneous encode
.Sp
processes allowed. If you have an \s-1SMP\s0 system,
increase this number to use more processes. Note
that Grip must be restarted for changes in this
option to take effect.
.Ip "\s-1MP3\s0 \*(N'nice\*(T' value" 5
The \*(L'nice\*(R' (priority) level to run the \s-1MP3\s0 encode at.
.Sh "\s-1ID3\s0 options:"
.Ip "\s-1ID3\s0 Executable" 5
The full path to the program that will add \s-1ID3\s0 tags to an
\s-1MP3\s0 file
.Ip "\s-1ID3\s0 Command-line" 5
The arguments to be passed to the \s-1ID3\s0 program. The %
switches are translated as:
.Ip "\f(CW%n\fR" 10
Name of track
.Ip "\f(CW%t\fR" 10
Number of track
.Ip "\f(CW%a\fR" 10
Artist of current track
.Ip "\f(CW%A\fR" 10
Artist of the current disc
.Ip "\f(CW%d\fR" 10
Name of current disc
.Ip "\f(CW%g\fR" 10
\s-1ID3\s0 genre tag as a number
.Ip "\f(CW%G\fR" 10
\s-1ID3\s0 genre tag as a word
.Ip "\f(CW%y\fR" 10
Year of track
.Ip "\f(CW%f\fR" 10
Name of the \s-1MP3\s0 file
.Ip "Add \s-1ID3\s0 tags" 5
If selected this option will cause \s-1ID3\s0 tags to be added to
each \s-1MP3\s0 file after it is encoded.
.Sh "\s-1CDDB\s0 options:"
.Ip "Primary/Secondary \s-1CDDB\s0 server" 5
These are your servers for looking up disc
information over the net. If the disc is
not found on the primary server, the
secondary server will be checked.
.Ip "\s-1DB\s0 server" 5
The address of the \s-1CDDB\s0 server you wish to use.
.Ip "\s-1DB\s0 \s-1CGI\s0 path" 5
The path to the script on the server that handles \s-1HTTP\s0
requests. This is generally \*(L"\f(CW~cddb/cddb.cgi\fR\*(R" or
\*(L"\f(CWcgi-bin/cddb.cgi\fR\*(R".
.Ip "Perform \s-1CDDB\s0 lookup automatically" 5
If selected, Grip will always try
to look up an unknown disc. If not
selected, lookup must be initiated
manually.
.Sh "Proxy options:"
.Ip "Use proxy server" 5
If selected, \s-1CDDB\s0 requests will be sent through an
\s-1HTTP\s0 proxy (useful for people behind firewalls).
.Ip "Get server from \*(N'http_proxy\*(T' env. var:" 5
If set, Grip will try to read the http server/port information from
the environment variable \*(L"\f(CWhttp_proxy\fR\*(R", which should take the form
\*(L"\f(CWhttp://server:port\fR\*(R".
.Ip "Proxy server" 5
The address of the \s-1HTTP\s0 proxy server to be used.
.Ip "Proxy port" 5
The port to talk to the proxy on.
.Sh "Misc options:"
.Ip "Output directory" 5
The directory to place \s-1WAV\s0 and \s-1MP3\s0 files in. The same \*(L'\f(CW%\fR\*(R'
switches as in the rip/encode filenames can be used.
.Ip "Convert spaces to underscores" 5
If selected, this will cause all spaces in
filenames to underscores.
.Ip "Also underscore" 5
A list of characters to replace with underscores when
constructing filenames.
.Ip "Email address" 5
The email address to be used as a reply address when
submitting \s-1CDDB\s0 entries and bug reports.
.Ip "\s-1CD\s0 update program" 5
This program will be run whenever a disc is put in the
drive. All sensible \*(L'\f(CW%\fR\*(R' switches can be used. I use
this to call a program that generates a web page that
tells what \s-1CD\s0 I'm currently playing.
.Ip "Keep application minimum size" 5
If selected, Grip will always try to keep
its window a the minimum size possible.
.SH "Common Questions"
.Ip "Q:" 0
When I try to rip a track, I get X I/O errors. What gives?
.Ip "A:" 0
This seems to be a problem with non-thread-safe systems. Make sure your
system is safe for threads. This often seems to be associated with libc5.
.Ip "Q:" 0
I just get a message saying that the program can't access my drive. This
makes it hard to do much. Help!
.Ip "A:" 0
Your user account must have access to the cd device. See the
\*(L"Running Grip/\s-1GCD\s0\*(R" section for more information on this.
.Ip "Q:" 0
I can play cd's fine, but my ripper can't access the drive. Why not?
.Ip "A:" 0
Rippers (cdparanoia, at least) need access to the generic \s-1SCSI\s0 device as
well. See the \*(L"Running Grip/\s-1GCD\s0\*(R" section for more information on this.
.Ip "Q:" 0
The progress bar doesn't seem to be completely accurate when doing an
\s-1MP3\s0 encode. Why can't it get it right?
.Ip "A:" 0
The progress bar is done based on the size of the output file. If you
have the kbits/sec set properly, Grip should estimate the size
properly. Note that if you use variable bitrate encoding (supported by
encoders like \s-1LAME\s0 and xing) Grip has no way to accurately guess the
file size.
.Ip "Q:" 0
I can't get lame to work. How lame is that?
.Ip "A:" 0
Lame has trouble with long filenames. If you increase \s-1MAX_NAME_SIZE\s0 in
the common.h file of the lame source distribution, it works fine.
.Ip "Q:" 0
When I encode tracks, the \s-1MP3\s0 progress bar never does anything. What
happened to progress?
.Ip "A:" 0
If your \s-1MP3\s0 encoder doesn't accept an output filename (like BladeEnc),
or you haven't passed it one on the command-line, then it might not be
outputting to the file Grip expects. Make sure that your \s-1MP3\s0 file format
is set to what your encoder is actually producing.
.Ip "Q:" 0
When Grip looks up disc information, it works, but says \*(L"Error saving
disc data\*(R". Why?
.Ip "A:" 0
Grip saves local copies of disc track information in the directory
\*(L"\f(CW~/.cddb\fR\*(R". It must be able to create or access this directory.
.Ip "Q:" 0
How come I don't get any scrollbars in the track display?
.Ip "A:" 0
You are using a version of Grip compiled for gtk+ v1.0.x on a system
that has gtk+ v1.1.x installed. You need to either get a binary compiled
for the development series of gtk+, or compile Grip yourself.
.Ip "Q:" 0
When my buddy runs Grip, he gets those nifty \s-1LCD\s0 icons showing
rip/encode/\s-1CDDB\s0 status, but I don't. What makes him so special?
.Ip "A:" 0
He's using a more recent version of gtk+ than you are. Due to bugs in
gtk+ v1.0.x, I don't support the icons under it. Upgrade your gtk+!
.Ip "Q:" 0
I can't get Grip to rip any tracks! This makes it less than useful...
.Ip "A:" 0
Grip won't rip tracks unless you tell it what to rip. Use the right
mouse button to select tracks for ripping.
.Ip "Q:" 0
Grip just hangs when doing a \s-1CDDB\s0 lookup. Why?
.Ip "A:" 0
If you are using Linux kernel 2.2.x, you need to compile Grip from
source. Installing the \s-1RPM\s0 results in network problems.
.Ip "Q:" 0
I was listening to a \s-1CD\s0 in Grip and it sounded horrible! What's up?
.Ip "A:" 0
Perhaps you are listening to country music...
.SH "CDDB notes"
I have declined to sign a license agreement with Escient, the company who
owns \*(L"www.cddb.com\*(R" and runs the CDDB server \*(L"us.cddb.com\*(R". Their license
would (among other things) have required me to place advertisements in Grip
and restrict you, the user, to use only their databases. I am against this
commercial use of the track information submitted by users such as
yourself. For this reason, I encourage you to use free servers, such as
\*(L"freecddb.freecddb.org\*(R".
.SH "License and Disclaimer"
Grip and GCD are Copyright (c) 1998 by Mike Oliphant. Grip and GCD may be
used and distributed under the terms of the GNU General Public License. All
other brand and product names are trademarks, registered trademarks or
service marks of their respective holders.
.PP
These programs are distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
more details.
.PP
You should have received a copy of the GNU General Public License along with
this distribution; if not, write to the Free Software Foundation, Inc., 59
Temple Place, Suite 330, Boston, MA 02111, USA.
.SH "Acknowledgments"
Thanks go to:
.Ip "\(bu" 5
Everyone involved in \s-1GTK\s0 development for a wonderful \s-1GUI\s0
.Ip "\(bu" 5
Tony Arcieri, for libcdaudio, which formed the basis of Grip's low-level
cd control and \s-1CDDB\s0 access routines
.Ip "\(bu" 5
Monty, for cdparanoia and the paranoia library
.Ip "\(bu" 5
Heiko Eissfeldt for cdda2wav
.Ip "\(bu" 5
Tord Jansson for BladeEnc
.Ip "\(bu" 5
Mike Cheng, Mark Taylor and all the others who have worked on \s-1LAME\s0
.Ip "\(bu" 5
Ti Kan, for the xmcd button bitmaps, many of which I use in modified form
.Ip "\(bu" 5
Everyone has contributed code to Grip (see the \s-1CREDITS\s0 file)
.Ip "\(bu" 5
Everyone else who has given me feedback and helped test Grip
.SH "CHANGES"
See the README file that came with the source code.
.SH "AUTHOR"
Grip and GCD written by Mike Oliphant (\f(CWoliphant@gtk.org\fR)
.PP
Documentation formatting by Aaron Sherman (\f(CWajs@ajs.com\fR)
.PP
.Vb 1
\&  http://www.nostatic.org/grip
.Ve

.rn }` ''
.IX Title "GRIP 1"
.IX Name "grip - A gtk-based cd-player and cd-ripper."

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "DESCRIPTION"

.IX Header "OPTIONS"

.IX Item "\f(CW-d <device>\fR"

.IX Item "\f(CW-s\fR"

.IX Item "\f(CW-l\fR"

.IX Item "\f(CW-v\fR"

.IX Item "\f(CW-d <device>\fR"

.IX Item "\f(CW-f\fR"

.IX Item "\f(CW-l\fR"

.IX Item "\f(CW-v\fR"

.IX Header "USAGE"

.IX Header "CONFIGURATION"

.IX Subsection "\s-1CD\s0 options:"

.IX Item "Don't interrupt playback on exit/startup"

.IX Item "Rewind when stopped"

.IX Item "Startup with first track if not playing"

.IX Item "Reshuffle before each playback"

.IX Item "\fBRipper\fR"

.IX Item "Disable paranoia"

.IX Item "Disable extra paranoia"

.IX Item "Disable scratch detection"

.IX Item "Disable scratch repair"

.IX Item "Ripping executable"

.IX Item "Ripping command-line"

.IX Item "\f(CW%t\fR"

.IX Item "\f(CW%b\fR"

.IX Item "\f(CW%e\fR"

.IX Item "\f(CW%f\fR"

.IX Item "Rip file format"

.IX Item "\f(CW%n\fR"

.IX Item "\f(CW%t\fR"

.IX Item "\f(CW%a\fR"

.IX Item "\f(CW%A\fR"

.IX Item "\f(CW%d\fR"

.IX Item "\f(CW%b\fR"

.IX Item "\f(CW%e\fR"

.IX Item "\f(CW%c\fR"

.IX Item "\f(CW%i\fR"

.IX Item "\f(CW%g\fR"

.IX Item "\f(CW%G\fR"

.IX Item "Rip \*(N'nice\*(T' value"

.IX Item "Max non-encoded \f(CW.wav\fR's"

.IX Item "Auto-rip on insert"

.IX Item "Auto-eject after rip"

.IX Item "Wav filter command"

.IX Subsection "\s-1MP3\s0 options:"

.IX Item "Encoder"

.IX Item "\s-1MP3\s0 executable"

.IX Item "\s-1MP3\s0 command-line"

.IX Item "\f(CW%b\fR"

.IX Item "\f(CW%f\fR"

.IX Item "\f(CW%o\fR"

.IX Item "\s-1MP3\s0 file format"

.IX Item "Delete \f(CW.wav\fR after encoding?"

.IX Item "Insert into \s-1SQL\s0 database"

.IX Item "Number of CPUs to use"

.IX Item "\s-1MP3\s0 \*(N'nice\*(T' value"

.IX Subsection "\s-1ID3\s0 options:"

.IX Item "\s-1ID3\s0 Executable"

.IX Item "\s-1ID3\s0 Command-line"

.IX Item "\f(CW%n\fR"

.IX Item "\f(CW%t\fR"

.IX Item "\f(CW%a\fR"

.IX Item "\f(CW%A\fR"

.IX Item "\f(CW%d\fR"

.IX Item "\f(CW%g\fR"

.IX Item "\f(CW%G\fR"

.IX Item "\f(CW%y\fR"

.IX Item "\f(CW%f\fR"

.IX Item "Add \s-1ID3\s0 tags"

.IX Subsection "\s-1CDDB\s0 options:"

.IX Item "Primary/Secondary \s-1CDDB\s0 server"

.IX Item "\s-1DB\s0 server"

.IX Item "\s-1DB\s0 \s-1CGI\s0 path"

.IX Item "Perform \s-1CDDB\s0 lookup automatically"

.IX Subsection "Proxy options:"

.IX Item "Use proxy server"

.IX Item "Get server from \*(N'http_proxy\*(T' env. var:"

.IX Item "Proxy server"

.IX Item "Proxy port"

.IX Subsection "Misc options:"

.IX Item "Output directory"

.IX Item "Convert spaces to underscores"

.IX Item "Also underscore"

.IX Item "Email address"

.IX Item "\s-1CD\s0 update program"

.IX Item "Keep application minimum size"

.IX Header "Common Questions"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Item "Q:"

.IX Item "A:"

.IX Header "CDDB notes"

.IX Header "License and Disclaimer"

.IX Header "Acknowledgments"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Item "\(bu"

.IX Header "CHANGES"

.IX Header "AUTHOR"

